# backend.py

import io
import os
import requests
from dotenv import load_dotenv
from fpdf import FPDF
from openai import OpenAI
import streamlit as st


# Initialize OpenAI Client securely
def get_openai_client():
    load_dotenv()
    api_key = os.getenv("OPENAI_API_KEY")

    if not api_key and "OPENAI_API_KEY" in st.secrets:
        api_key = st.secrets["OPENAI_API_KEY"]

    if not api_key:
        return None

    return OpenAI(api_key=api_key)


# Generate Streaming Response from OpenAI
def get_ai_stream(client, chat_history, system_prompt):
    messages_to_send = [{"role": "system", "content": system_prompt}]
    messages_to_send.extend(chat_history)

    return client.chat.completions.create(
        model="gpt-4o-mini",
        messages=messages_to_send,
        temperature=0.7,
        stream=True,
    )


# Generate PDF Summary Stream (Fixed X-position bug)
def generate_pdf(summary_text: str) -> bytes:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(15, 15, 15)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Printable width: A4 width (210mm) - 2 * margins (30mm) = 180mm
    PRINT_WIDTH = 180

    # Header Banner
    pdf.set_fill_color(2, 132, 199)
    pdf.rect(0, 0, 210, 32, "F")

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(15, 8)
    pdf.cell(PRINT_WIDTH, 10, "Patient Pre-Visit Summary")

    pdf.set_xy(15, 18)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(PRINT_WIDTH, 4, "Generated by ClinicalPrep AI Assistant")

    pdf.set_xy(15, 38)  # Position cleanly below the header banner

    # Clean markdown formatting tags and unsupported unicode characters
    clean_text = (
        summary_text.replace("🩺", "")
        .replace("**", "")
        .replace("###", "")
        .replace("####", "")
        .replace("#", "")
        .replace("’", "'")
        .replace("“", '"')
        .replace("”", '"')
        .replace("–", "-")
        .replace("—", "-")
        .replace("•", "-")
    )

    pdf.set_text_color(30, 41, 59)
    pdf.set_font("Helvetica", "", 10)

    for line in clean_text.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue

        # Force X position to left margin before each multi_cell call
        pdf.set_x(15)

        if (
            line.startswith("1.")
            or line.startswith("2.")
            or line.startswith("3.")
            or "Chief Complaint" in line
            or "Current Interventions" in line
            or "Top Questions" in line
        ):
            pdf.ln(2)
            pdf.set_x(15)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(3, 105, 161)
            pdf.multi_cell(PRINT_WIDTH, 6, line)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 41, 59)
        elif line.startswith("*"):
            formatted_bullet = f"- {line[1:].strip()}"
            pdf.multi_cell(PRINT_WIDTH, 5, formatted_bullet)
        else:
            pdf.multi_cell(PRINT_WIDTH, 5, line)

    # Footer Notice
    pdf.set_y(-20)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.multi_cell(
        PRINT_WIDTH,
        4,
        "Notice: This pre-visit summary was generated automatically to assist your upcoming medical consultation. It is not medical advice or a formal diagnosis.",
        align="C",
    )

    pdf_output = io.BytesIO()
    pdf.output(pdf_output)
    return pdf_output.getvalue()


# Helper to fetch Lottie animation JSON
def load_lottie_url(url: str):
    try:
        r = requests.get(url, timeout=5)
        if r.status_code == 200:
            return r.json()
    except Exception:
        return None