# src/utils/pdf_generator.py
import io
import re
from fpdf import FPDF


def generate_pdf(summary_text: str) -> bytes:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(15, 15, 15)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    PRINT_WIDTH = 180  # A4 210mm - 30mm margins

    # 1. Header Banner Block (Bold, Large Headline Header)
    pdf.set_fill_color(2, 132, 199)  # Medical Blue
    pdf.rect(0, 0, 210, 30, "F")

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(15, 7)
    pdf.cell(PRINT_WIDTH, 10, "Patient Pre-Visit Summary", align="L")

    pdf.set_xy(15, 18)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(PRINT_WIDTH, 4, "Generated by ClinicalPrep AI Assistant", align="L")

    pdf.set_xy(15, 36)

    # Clean text input & discard introductory chat text
    lines = summary_text.split("\n")
    start_idx = 0
    for idx, line in enumerate(lines):
        if "Patient Pre-Visit Summary" in line:
            start_idx = idx
            break

    summary_lines = lines[start_idx:]

    date_str = ""
    content_lines = []

    for line in summary_lines:
        # Ignore intro chat phrases and sidebar download notices in PDF output
        if "Here's your" in line or "Your summary PDF is automatically generated" in line:
            continue
        if "Date:" in line:
            clean_date = line.replace("**", "").replace("🩺", "").strip()
            date_str = clean_date
        else:
            content_lines.append(line)

    # 2. Date Right-Aligned on the Next Line
    if date_str:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(71, 85, 105)  # Slate Gray
        pdf.cell(PRINT_WIDTH, 6, date_str, align="R")
        pdf.ln(8)
    else:
        pdf.ln(2)

    pdf.set_text_color(30, 41, 59)
    pdf.set_font("Helvetica", "", 10)

    q_counter = 0  # Counter for a., b., c. sub-points
    in_top_questions = False

    for line in content_lines:
        clean_line = (
            line.replace("🩺", "")
            .replace("**", "")
            .replace("###", "")
            .replace("####", "")
            .replace("#", "")
            .replace("’", "'")
            .replace("“", '"')
            .replace("”", '"')
            .replace("–", "-")
            .replace("—", "-")
            .replace("•", "-")
            .strip()
        )

        if not clean_line or clean_line == "Patient Pre-Visit Summary":
            continue

        pdf.set_x(15)

        # 3. Section Sequencing
        if "Patient Information" in clean_line:
            clean_line = "1. Patient Information"
            in_top_questions = False
        elif "Chief Complaint" in clean_line:
            clean_line = "2. Chief Complaint & History of Present Illness"
            in_top_questions = False
        elif "Current Interventions" in clean_line:
            clean_line = "3. Current Interventions"
            in_top_questions = False
        elif "Top Questions" in clean_line or "Points for the Doctor" in clean_line:
            clean_line = "4. Top Questions / Points for the Doctor"
            in_top_questions = True
            q_counter = 0

        # Render Section Headings
        if (
            clean_line.startswith("1.")
            or clean_line.startswith("2.")
            or clean_line.startswith("3.")
            or clean_line.startswith("4.")
        ):
            pdf.ln(3)
            pdf.set_x(15)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(3, 105, 161)  # Medical Blue
            pdf.multi_cell(PRINT_WIDTH, 6, clean_line)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 41, 59)

        # 4. Sub-points formatting (a., b., c...) under Section 4
        elif in_top_questions and (
            re.match(r"^(\d+|[a-zA-Z])[\.\)]", clean_line) or clean_line.startswith("-")
        ):
            item_text = re.sub(r"^(\d+|[a-zA-Z])[\.\)]\s*", "", clean_line).strip()
            if item_text.startswith("-"):
                item_text = item_text[1:].strip()

            # Filter out empty, placeholder, or dash items like '--', '-', 'None'
            if not item_text or item_text in ["--", "-", "None", "None reported", "N/A"]:
                continue

            q_counter += 1
            letter_prefix = chr(96 + q_counter)  # 1 -> 'a', 2 -> 'b', 3 -> 'c'
            pdf.set_x(20)  # Indent sub-points
            pdf.multi_cell(PRINT_WIDTH - 5, 5, f"{letter_prefix}. {item_text}")

        elif clean_line.startswith("*"):
            pdf.set_x(15)
            pdf.multi_cell(PRINT_WIDTH, 5, f"- {clean_line[1:].strip()}")
        else:
            pdf.set_x(15)
            pdf.multi_cell(PRINT_WIDTH, 5, clean_line)

    # Footer Disclaimer
    pdf.set_y(-20)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.multi_cell(
        PRINT_WIDTH,
        4,
        "Notice: This pre-visit summary was generated automatically to assist your upcoming medical consultation. It is not medical advice or a formal diagnosis.",
        align="C",
    )

    pdf_output = io.BytesIO()
    pdf.output(pdf_output)
    return pdf_output.getvalue()